name: CI

on:
  push:
    branches-ignore:
      - "wip*"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: Julian/setup-lean@c93774d9180849a5b6c4034c3c63d4544bdd943c

      - name: Set up PyPy 2.7
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "pypy-2.7"

      - name: Checkout PyPy
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: pypy/pypy
          path: pypy
          persist-credentials: false
      - run: pypy --version

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 #v4.0.0

      - name: Create .env file
        run: |
          cat << EOF > .env
          PYPY_CHECKOUT=./pypy
          EOF

      - name: Run Tests
        run: just test

      - name: Translate
        run: just translate

      - name: Run Post-Translation Tests
        run: just test-translated

      - name: Upload Translated Binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rpylean-${{ runner.os }}-${{ matrix.arch }}
          path: ./rpylean-c
